spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    host: smtp.gmail.com
    username: servetozboke@gmail.com
    password: qafowzjyvsqnmotx
    port: 587


rabbitmq:
  password: guest
  queue: rabbitmq.queue
  register: rabbitmq.json_register
  signup: rabbitmq.json_signup
  max:
    concurrent:
      consumers: '1'
  reply:
    timeout: '60000'
  username: guest
  exchange: rabbitmq.exchange
  port: '15672'
  concurrent:
    consumers: '1'
  host: localhost
  virtualhost: /
  routingkey: rabbitmq.routingkey
  routing_register_key: rabbitmq.routing_register_key
  routing_signup_key: rabbitmq.routing_signup_key
